title: Kumar Vishnu Yadav
description: MSc Computer Science (Data Science â€“ Deep Learning)
theme: jekyll-theme-minimal

github:
  is_project_page: false

social_links:
  github: vishnu-devx
  # linkedin: your-linkedin-username

